server:
  port: 8080

spring:
  application:
    name: brainventory-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: humanResources
          uri: lb://HUMAN-RESOURCES
          predicates:
            - Path=/api/employee/**,/api/job-role/**
        - id: infrastructure
          uri: lb://INFRASTRUCTURE
          predicates:
            - Path=/api/building/**,/api/room/**,/api/room-device/**,/api/department/**
        - id: assets
          uri: lb://ASSETS
          predicates:
            - Path=/api/it-device/**,/api/io-device/**,/api/hardware/**
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**,/profile/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false