server:
  port: 8888

spring:
  application:
    name: brainventory-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations